version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000" # HOST:CONTAINER
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      # the variables below must match those defined in the db service
      - DB_HOST=db # because we are using docker compose we can just use the name of the service
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      # set three environment variables to set the initial database
      # configuration for our new db service.
      - POSTGRES_DB=devdb #
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme




volumes:
  dev-db-data: # name of our volume


